services:
  - type: web
    name: fastapi-selenium-app
    runtime: python
    buildCommand: |
      apt-get update && \
      apt-get install -y chromium-browser chromium-chromedriver && \
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
